### ISSUE TITLE
Resume

### ISSUE THREAD

**Issue by vdalv** [iptq/iptq.github.io#7]
![](https://i.imgur.com/zeKGC2Q.png)
1. Now is spelled 'now' as well as 'Now'.
I'd recommend using 'Present' instead of 'Now'.

2. blog.michaelz.xyz is a broken link, need to replace w/ blog.mzhang.me

3. Not sure if me@michaelz.xyz​ is working considering michaelz.xyz isn't...

4. Link is incorrect.
![](https://i.imgur.com/DmTf9IV.png)

**Comment by iptq** [comment]
yea that domain expired and i didnt feel liek renewing, thank4 commenting anyway,,,,
